services:
  app:
    build: .
    ports:
      - "5000:5000" 
    volumes:
      - type: bind
        source: flask
        target: /usr/src/app/
    networks:
      - net
    secrets:
      - api_key

secrets:
  api_key:
    file: api_key.txt
  
networks:
  net:
