services:
  app:
    build: .
    ports:
      - "80:80" 
    volumes:
      - type: bind
        source: flask
        target: /usr/src/app/
      - type: bind
        source: frontend
        target: /usr/src/frontend/
      - type: bind
        source: nginx
        target: /etc/nginx/sites-available
    networks:
      - net
    secrets:
      - api_key

secrets:
  api_key:
    file: api_key.txt
  
networks:
  net:
